import classNames from "classnames";
import Head from "next/head";
import Image from "next/image";
import useSWR, { mutate } from "swr";
import axios from "axios";
import styles from "../styles/Home.module.css";
const fetcher = (...args) => axios(...args).then((res) => res.data);

const API_PATH = "/api/song";

const putEntry = async (payload) => {
  return fetch(API_PATH, {
    method: "POST",
    body: JSON.stringify(payload),
    headers: {
      "Content-Type": "application/json",
    },
  }).then((res) => (res.ok ? res.json() : Promise.reject(res)));
};

export default function Home() {
  const { data: songList, error } = useSWR(API_PATH, fetcher);

  const addSong = async (item) => {
    const responseResult = await putEntry(item);
    console.log(responseResult);
    if (responseResult.response?.errors) {
      console.log(
        responseResult.response.errors.map(({ message }) => message).join("\n")
      );
    } else {
      console.log(JSON.stringify(responseResult));
    }
    await mutate(API_PATH);
  };

  if (!songList) {
    return null;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="navbar navbar-expand-lg bg-light">
  <div className="container-fluid">
    <a className="navbar-brand" href="#">Navbar</a>
    <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span className="navbar-toggler-icon"></span>
    </button>
    <div className="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div className="navbar-nav">
        <a className="nav-link active" aria-current="page" href="#">Home</a>
        <a className="nav-link" href="#">Features</a>
        <a className="nav-link" href="#">Pricing</a>
        <a className="nav-link disabled">Disabled</a>
      </div>
    </div>
  </div>
</nav>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          {newSong.map(({ data }, index) => (
            <div
              className={classNames(styles.card, {
                [styles["-done"]]: songList.find(
                  ({ name }) => name === data.name
                ),
              })}
              key={index}
              onClick={() => addSong(data)}
            >
              <p>{data.name}</p>
            </div>
          ))}
        </div>
        <div className={styles.grid}>
          {songList.map((item) => (
            <div className={styles.card} key={item._id}>
              <p>{item.name}</p>
              <p>{item.artist.name}</p>
            </div>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
const newSong = [
  {
    data: {
      name: "I'm not sorry",
      type: "LIMITED",
      artist: { connect: "339975409844093516" },
      length: 3,
      card: ["R1", "R1", "R1"],
    },
  },
];
